# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-10 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('user', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('total_ganho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('start_prize', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('img', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='id_time_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='blog.Time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='id_time_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='blog.Time'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='id_jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to='blog.Jogador'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='id_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida', to='blog.Partida'),
        ),
    ]
