# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='dinheiro',
            new_name='saldo',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='total_ganho',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='start_prize',
        ),
        migrations.AddField(
            model_name='aposta',
            name='gols_time_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aposta',
            name='gols_time_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='gol_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='gol_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='id_jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Jogador'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='id_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Partida'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
