# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180417_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='id_time_1',
            new_name='time_casa',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='id_time_2',
            new_name='time_visitante',
        ),
    ]
