# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180417_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='img',
        ),
    ]
