# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_time_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
