# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-17 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180417_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='password',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='jogador',
            old_name='user',
            new_name='usuario',
        ),
    ]
