# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180418_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='usuario',
        ),
    ]
