# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180418_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='id_jogador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
