# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180418_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
