# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180418_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='id_jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
