# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180418_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gols_time_casa', models.IntegerField(default=0)),
                ('gols_time_visitante', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='partida',
            name='gol_casa',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='gol_visitante',
        ),
        migrations.AddField(
            model_name='resultado',
            name='id_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Partida'),
        ),
    ]
