# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_partida_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id_partida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Partida'),
        ),
    ]
