# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180418_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='id_jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Jogador'),
        ),
    ]
